global:
  evaluation_interval: 30s
  scrape_interval: 1s
scrape_configs:
- job_name: otel
  static_configs:
  - targets:
    - otelcol:9464
- job_name: otel-collector
  static_configs:
  - targets:
    - otelcol:8888
- job_name: docker
  static_configs:
  - targets:
    - docker.for.mac.localhost:9323
