global:
  evaluation_interval: 30s
  scrape_interval: 1s
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - otelcol:8888
- job_name: cadvisor
  scrape_interval: 1s
  static_configs:
  - targets:
    - cadvisor:8181
